// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacedReptititonSystem;

namespace CapitalCities.Migrations
{
    [DbContext(typeof(CapitalCityDbContext))]
    [Migration("20190428091639_NewDatabase")]
    partial class NewDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacedReptititonSystem.CapitalCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capital");

                    b.Property<string>("Country");

                    b.Property<bool>("IsCurrent");

                    b.Property<DateTime>("LastStudied");

                    b.Property<int>("Score");

                    b.Property<int>("StudyOrder");

                    b.HasKey("Id");

                    b.ToTable("CapitalCities");
                });
#pragma warning restore 612, 618
        }
    }
}
